<?php

namespace RoNoLo\Flydb;

/**
 * Document
 *
 * Represents a document in Flywheel. Essentially this is a Plain Old PHP
 * Object (POPO).
 *
 * The only important property on this object is $__flywheelDocId. It's used
 * to ensure uniqueness when storing a document. You can set this yourself using
 * the `setId()` method or if omitted it will be autogenerated for you.
 */
class Document implements DocumentInterface
{
    protected $data;

    protected $id = null;

    /**
     * Constructor
     *
     * @param array $data array or object
     */
    public function __construct($data)
    {
        $this->data = $data;
    }

    /**
     * Get the document ID.
     *
     * @return null|string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    public function getPayload(): array
    {
        return $this->data;
    }

    public function asArray(): array
    {
        return [
            '__id' => $this->id,
            'payload' => $this->data,
        ];
    }
}
